return {
  ["Car"] = { ru = "Авто", zh = "载具", ja = "車両", vi = "Xe", id = "Mobil" },
  ["ESP"] = { ru = "ESP", zh = "透视", ja = "ESP", vi = "ESP", id = "ESP" },
  ["Lang"] = { ru = "Язык", zh = "语言", ja = "言語", vi = "Ngôn ngữ", id = "Bahasa" },
  ["Players"] = { ru = "Игроки", zh = "玩家", ja = "プレイヤー", vi = "Người chơi", id = "Pemain" },
  ["Radar"] = { ru = "Радар", zh = "雷达", ja = "レーダー", vi = "Radar", id = "Radar" },
  ["World"] = { ru = "Мир", zh = "世界", ja = "ワールド", vi = "Thế giới", id = "Dunia" },
  ["Misc"] = { ru = "Разное", zh = "杂项", ja = "その他", vi = "Khác", id = "Lainnya" },
  ["Exploits"] = { ru = "Эксплойты", zh = "漏洞利用", ja = "エクスプロイト", vi = "Khai thác", id = "Eksploit" },

  ["Aimbot:This decsription for child"] = { ru = "Аимбот:Настройка автонаведения", zh = "自瞄:瞄准辅助设置", ja = "エイムボット:照準補助の設定", vi = "Aimbot:Cài đặt ngắm tự động", id = "Aimbot:Pengaturan bidik otomatis" },
  ["Menu settings:This decsription for child"] = { ru = "Настройки меню:Основные параметры", zh = "菜单设置:常规选项", ja = "メニュー設定:基本オプション", vi = "Cài đặt menu:Tùy chọn chung", id = "Pengaturan menu:Opsi umum" },
  ["Wallhack:This decsription for child"] = { ru = "Wallhack:Видеть сквозь стены", zh = "透视:穿墙显示", ja = "ウォールハック:壁越し表示", vi = "Wallhack:Nhìn xuyên tường", id = "Wallhack:Lihat tembus dinding" },
  ["Combat Settings:Esp features"] = { ru = "Бой:Функции ESP", zh = "战斗设置:ESP功能", ja = "戦闘設定:ESP機能", vi = "Chiến đấu:Tính năng ESP", id = "Tempur:Fitur ESP" },
  ["ESP Preview:Esp visible items change"] = { ru = "Превью ESP:Настройка отображения", zh = "透视预览:显示项设置", ja = "ESPプレビュー:表示項目の設定", vi = "Xem trước ESP:Cài đặt hiển thị", id = "Pratinjau ESP:Pengaturan tampilan" },

  ["Target Prediction"] = { ru = "Предсказание цели", zh = "目标预测", ja = "ターゲット予測", vi = "Dự đoán mục tiêu", id = "Prediksi target" },
  ["Strength"] = { ru = "Сила", zh = "强度", ja = "強度", vi = "Sức mạnh", id = "Kekuatan" },
  ["Mode"] = { ru = "Режим", zh = "模式", ja = "モード", vi = "Chế độ", id = "Mode" },
  ["Visualize path"] = { ru = "Показ траектории", zh = "显示轨迹", ja = "軌道を表示", vi = "Hiện đường đạn", id = "Tampilkan jalur" },
  ["Velocity"] = { ru = "Скорость", zh = "速度", ja = "速度", vi = "Vận tốc", id = "Kecepatan" },
  ["Acceleration"] = { ru = "Ускорение", zh = "加速度", ja = "加速度", vi = "Gia tốc", id = "Akselerasi" },
  ["Hybrid"] = { ru = "Гибрид", zh = "混合", ja = "ハイブリッド", vi = "Hybrid", id = "Hibrida" },

  ["Radar Range"] = { ru = "Радиус радара", zh = "雷达范围", ja = "レーダー範囲", vi = "Phạm vi radar", id = "Jangkauan radar" },
  ["Radar Mode"] = { ru = "Режим радара", zh = "雷达模式", ja = "レーダーモード", vi = "Chế độ radar", id = "Mode radar" },
  ["Footprints"] = { ru = "Следы", zh = "脚印", ja = "足跡", vi = "Dấu chân", id = "Jejak kaki" },
  ["Footprint Type"] = { ru = "Тип следов", zh = "脚印类型", ja = "足跡の種類", vi = "Loại dấu chân", id = "Tipe jejak" },
  ["Bones"] = { ru = "Кости", zh = "骨骼", ja = "ボーン", vi = "Xương", id = "Tulang" },
  ["Head"] = { ru = "Голова", zh = "头部", ja = "頭", vi = "Đầu", id = "Kepala" },
  ["Chest"] = { ru = "Грудь", zh = "胸部", ja = "胸", vi = "Ngực", id = "Dada" },
  ["Pelvis"] = { ru = "Таз", zh = "骨盆", ja = "骨盤", vi = "Xương chậu", id = "Panggul" },
  ["Arms"] = { ru = "Руки", zh = "手臂", ja = "腕", vi = "Tay", id = "Lengan" },
  ["Legs"] = { ru = "Ноги", zh = "腿部", ja = "脚", vi = "Chân", id = "Kaki" },
  ["None"] = { ru = "Нет", zh = "无", ja = "なし", vi = "Không", id = "Tidak ada" },

  ["Tracer Color"] = { ru = "Цвет трассера", zh = "弹道颜色", ja = "トレーサー色", vi = "Màu vạch đạn", id = "Warna tracer" },
  ["Tracer Count"] = { ru = "Кол-во трассеров", zh = "弹道数量", ja = "トレーサー数", vi = "Số vạch đạn", id = "Jumlah tracer" },
  ["Recoil Level"] = { ru = "Уровень отдачи", zh = "后座力等级", ja = "リコイルレベル", vi = "Mức giật", id = "Tingkat recoil" },

  ["Particle count"] = { ru = "Кол-во частиц", zh = "粒子数量", ja = "パーティクル数", vi = "Số hạt", id = "Jumlah partikel" },
  ["First gradient color"] = { ru = "Первый цвет градиента", zh = "渐变起始色", ja = "グラデーション開始色", vi = "Màu gradient đầu", id = "Warna gradien awal" },
  ["Second gradient color"] = { ru = "Второй цвет градиента", zh = "渐变结束色", ja = "グラデーション終了色", vi = "Màu gradient cuối", id = "Warna gradien akhir" },
  ["Username"] = { ru = "Имя пользователя", zh = "用户名", ja = "ユーザー名", vi = "Tên người dùng", id = "Nama pengguna" },

  ["Select gun"] = { ru = "Выбор оружия", zh = "选择武器", ja = "武器を選択", vi = "Chọn súng", id = "Pilih senjata" },
  ["Enable Wallhack"] = { ru = "Включить Wallhack", zh = "启用透视", ja = "ウォールハックを有効化", vi = "Bật Wallhack", id = "Aktifkan Wallhack" },
  ["Show Enemies"] = { ru = "Показ врагов", zh = "显示敌人", ja = "敵を表示", vi = "Hiện kẻ địch", id = "Tampilkan musuh" },
  ["Show Health"] = { ru = "Показ здоровья", zh = "显示血量", ja = "体力を表示", vi = "Hiện máu", id = "Tampilkan HP" },
  ["Show Armor"] = { ru = "Показ брони", zh = "显示护甲", ja = "アーマーを表示", vi = "Hiện giáp", id = "Tampilkan armor" },
  ["Enemy Color"] = { ru = "Цвет врага", zh = "敌人颜色", ja = "敵の色", vi = "Màu kẻ địch", id = "Warna musuh" },
  ["Item Color"] = { ru = "Цвет предметов", zh = "物品颜色", ja = "アイテムの色", vi = "Màu vật phẩm", id = "Warna item" },
  ["Max Distance"] = { ru = "Макс. дистанция", zh = "最大距离", ja = "最大距離", vi = "Khoảng cách tối đa", id = "Jarak maksimum" },
  ["Wallhack"] = { ru = "Wallhack", zh = "透视", ja = "ウォールハック", vi = "Wallhack", id = "Wallhack" },

  ["Language"] = { ru = "Язык", zh = "语言", ja = "言語", vi = "Ngôn ngữ", id = "Bahasa" },
  ["Font weight"] = { ru = "Толщина шрифта", zh = "字体粗细", ja = "フォントの太さ", vi = "Độ đậm chữ", id = "Ketebalan font" },
  ["Animation side"] = { ru = "Сторона анимации", zh = "动画方向", ja = "アニメの向き", vi = "Hướng hoạt ảnh", id = "Arah animasi" },
  ["Disable animations"] = { ru = "Откл. анимации", zh = "禁用动画", ja = "アニメ無効", vi = "Tắt hoạt ảnh", id = "Matikan animasi" },
  ["Disable appear anim"] = { ru = "Откл. анимацию появления", zh = "禁用弹出动画", ja = "出現アニメ無効", vi = "Tắt hoạt ảnh xuất hiện", id = "Matikan animasi muncul" },

  ["Regular"] = { ru = "Обычный", zh = "常规", ja = "標準", vi = "Thường", id = "Reguler" },
  ["Medium"] = { ru = "Средний", zh = "中等", ja = "中字", vi = "Vừa", id = "Sedang" },
  ["SemiBold"] = { ru = "Полужирный", zh = "半粗体", ja = "中太", vi = "Đậm vừa", id = "Semi-tebal" },
  ["Left"] = { ru = "Слева", zh = "左", ja = "左", vi = "Trái", id = "Kiri" },
  ["Right"] = { ru = "Справа", zh = "右", ja = "右", vi = "Phải", id = "Kanan" },
  ["Off"] = { ru = "Выкл", zh = "关闭", ja = "オフ", vi = "Tắt", id = "Mati" },
  ["Minimal"] = { ru = "Минимум", zh = "简略", ja = "最小", vi = "Tối thiểu", id = "Minimal" },
  ["Full"] = { ru = "Полный", zh = "完整", ja = "フル", vi = "Đầy đủ", id = "Penuh" },
  ["Low"] = { ru = "Низкий", zh = "低", ja = "低", vi = "Thấp", id = "Rendah" },
  ["High"] = { ru = "Высокий", zh = "高", ja = "高", vi = "Cao", id = "Tinggi" },
  ["Pistol"] = { ru = "Пистолет", zh = "手枪", ja = "ピストル", vi = "Súng lục", id = "Pistol" },
  ["Rifle"] = { ru = "Винтовка", zh = "步枪", ja = "ライフル", vi = "Súng trường", id = "Senapan" },
  ["Sniper"] = { ru = "Снайперка", zh = "狙击枪", ja = "スナイパー", vi = "Súng bắn tỉa", id = "Sniper" },
  ["Shotgun"] = { ru = "Дробовик", zh = "霰弹枪", ja = "ショットガン", vi = "Súng shotgun", id = "Shotgun" },

  ["Hold"] = { ru = "Удержание", zh = "按住", ja = "長押し", vi = "Giữ", id = "Tahan" },
  ["Toggle"] = { ru = "Переключение", zh = "切换", ja = "切替", vi = "Bật/tắt", id = "Alih" },
  ["Always"] = { ru = "Всегда", zh = "始终", ja = "常時", vi = "Luôn", id = "Selalu" },

  ["SAVE CONFIG"] = { ru = "СОХРАНИТЬ КОНФИГ", zh = "保存配置", ja = "設定を保存", vi = "LƯU CẤU HÌNH", id = "SIMPAN KONFIG" },
  ["CHANGE THEME"] = { ru = "СМЕНИТЬ ТЕМУ", zh = "切换主题", ja = "テーマを変更", vi = "ĐỔI GIAO DIỆN", id = "GANTI TEMA" },
  ["Light theme"] = { ru = "Светлая тема", zh = "浅色主题", ja = "ライトテーマ", vi = "Giao diện sáng", id = "Tema terang" },
  ["Dark theme"] = { ru = "Тёмная тема", zh = "深色主题", ja = "ダークテーマ", vi = "Giao diện tối", id = "Tema gelap" },
  ["Config saved"] = { ru = "Конфиг сохранён", zh = "配置已保存", ja = "設定を保存しました", vi = "Đã lưu cấu hình", id = "Konfig disimpan" },

  ["Settings"] = { ru = "Настройки", zh = "设置", ja = "設定", vi = "Cài đặt", id = "Pengaturan" },
  ["Fine-tuning for sure wins"] = { ru = "Тонкая настройка ради побед", zh = "精细调校，稳操胜券", ja = "勝利のための微調整", vi = "Tinh chỉnh để chắc thắng", id = "Penyetelan untuk menang" },

  ["Enter name..."] = { ru = "Введите имя...", zh = "输入名称...", ja = "名前を入力...", vi = "Nhập tên...", id = "Masukkan nama..." },
  ["Distance"] = { ru = "Дистанция", zh = "距离", ja = "距離", vi = "Khoảng cách", id = "Jarak" },
  ["Flashed"] = { ru = "Ослеплён", zh = "致盲", ja = "フラッシュ中", vi = "Bị lóa", id = "Silau" },
  ["Scoped"] = { ru = "В прицеле", zh = "开镜", ja = "スコープ中", vi = "Đang ngắm", id = "Buka scope" },
  ["Money"] = { ru = "Деньги", zh = "金钱", ja = "資金", vi = "Tiền", id = "Uang" },
  ["Zoom"] = { ru = "Зум", zh = "缩放", ja = "ズーム", vi = "Zoom", id = "Zoom" },
  ["Hit"] = { ru = "Попадание", zh = "命中", ja = "命中", vi = "Trúng đạn", id = "Kena" },
  ["Defusing"] = { ru = "Разминирует", zh = "拆弹中", ja = "解除中", vi = "Đang gỡ bom", id = "Menjinakkan" },
  ["Bomb"] = { ru = "Бомба", zh = "炸弹", ja = "爆弾", vi = "Bom", id = "Bom" },
  ["LC"] = { ru = "LC", zh = "LC", ja = "LC", vi = "LC", id = "LC" },
}
